//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneTicket.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneTicket.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PhoneTicket] Confirmar registracion.
        /// </summary>
        public static string ConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://phoneticket.apphb.com/api/users/{0}/confirm?secret={1}.
        /// </summary>
        public static string ConfirmationLinkFormat {
            get {
                return ResourceManager.GetString("ConfirmationLinkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido no pudo ser interpretado. Verifique que el archivo este bien formado..
        /// </summary>
        public static string ErrorParsingContent {
            get {
                return ResourceManager.GetString("ErrorParsingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El atributo &apos;desde&apos; es obligatorio para los elementos de tipo &lt;Fila&gt;..
        /// </summary>
        public static string FromAttributeIsRequired {
            get {
                return ResourceManager.GetString("FromAttributeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El atributo &apos;desde&apos; debe ser menor o igual al atributo &apos;hasta&apos;..
        /// </summary>
        public static string FromHigherThanToError {
            get {
                return ResourceManager.GetString("FromHigherThanToError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El atributo &apos;desde&apos; debe ser un valor entre 1 y 22..
        /// </summary>
        public static string FromRangeError {
            get {
                return ResourceManager.GetString("FromRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor del campo debe ser mayor a 0..
        /// </summary>
        public static string GreaterThanZero {
            get {
                return ResourceManager.GetString("GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los elementos hijos de &lt;Sala&gt; deben ser de tipo &lt;Fila&gt;..
        /// </summary>
        public static string InvalidRoomChildElement {
            get {
                return ResourceManager.GetString("InvalidRoomChildElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El elemento raiz debe ser &lt;Sala&gt;..
        /// </summary>
        public static string InvalidRootElement {
            get {
                return ResourceManager.GetString("InvalidRootElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo es obligatorio..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El atributo &apos;numero&apos; es obligatorio para los elementos de tipo &lt;Fila&gt;..
        /// </summary>
        public static string RowNumberIsRequired {
            get {
                return ResourceManager.GetString("RowNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El atributo &apos;numero&apos; debe ser un valor entre 1 y 17..
        /// </summary>
        public static string RowNumberRangeError {
            get {
                return ResourceManager.GetString("RowNumberRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El atributo &apos;hasta&apos; es obligatorio para los elementos de tipo &lt;Fila&gt;..
        /// </summary>
        public static string ToAttributeIsRequired {
            get {
                return ResourceManager.GetString("ToAttributeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El atributo &apos;hasta&apos; debe ser un valor entre 1 y 22..
        /// </summary>
        public static string ToRangeError {
            get {
                return ResourceManager.GetString("ToRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor del campo debe ser una URL válida..
        /// </summary>
        public static string UrlField {
            get {
                return ResourceManager.GetString("UrlField", resourceCulture);
            }
        }
    }
}
