// <auto-generated />
namespace PhoneTicket.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class PurchaseModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PurchaseModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201310262216034_PurchaseModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
